### ISSUE TITLE
--pullrequestオプションにnil渡すとエラーになる

### ISSUE THREAD

**Issue by rvillage** [rvillage/pr-daikou#2]
```
/usr/local/bundle/gems/pr-daikou-0.0.1/lib/pr-daikou/cli.rb:25:in `parse': missing argument: --pullrequest (OptionParser::MissingArgument)
	from /usr/local/bundle/gems/pr-daikou-0.0.1/lib/pr-daikou/cli.rb:8:in `parse_options'
	from /usr/local/bundle/gems/pr-daikou-0.0.1/bin/pr-daikou:5:in `<top (required)>'
	from /usr/local/bundle/bin/pr-daikou:23:in `load'
	from /usr/local/bundle/bin/pr-daikou:23:in `<main>'
Exited with code 1
```

**Comment by rvillage** [comment]
✅ done!
